Added the missing include needed for linux compilation.
Added the -Wno-maybe-uninitialized flag for debug build to bypass the error due to an unused variable in googletest source code:
``gtest-death-test.cc:1301:24: error: 'dummy' may be used uninitialized [-Werror=maybe-uninitialized]`
`