Eliminates the unused field which caused compilation failures at windows. Example failure: C:\jenkins\ope-fs-root\workspace\cpp-windows-nightly-release\hazelcast\include\hazelcast/client/config/EvictionConfig.h(103): error C2039: 'auto_ptr' : is not a member of 'std' (C:\jenkins\ope-fs-root\workspace\cpp-windows-nightly-release\hazelcast\src\hazelcast\client\config\EvictionConfig.cpp) [c:\jenkins\ope-fs-root\workspace\cpp-windows-nightly-release\ReleaseShared64\HazelcastClient3.7-SNAPSHOT_64.vcxproj]