Added missing header for centos7 build.  (#385)
Centos 7 build error was:
```
 [01m [K<https://hazelcast-l337.ci.cloudbees.com/job/cpp-centos7-nightly-32-STATIC-Debug/ws/hazelcast/src/hazelcast/util/UuidUtil.cpp>: [m [K In static member function ‘ [01m [Kstatic hazelcast::util::UUID hazelcast::util::UuidUtil::newUnsecureUUID() [m [K’:
 [01m [K<https://hazelcast-l337.ci.cloudbees.com/job/cpp-centos7-nightly-32-STATIC-Debug/ws/hazelcast/src/hazelcast/util/UuidUtil.cpp>:29:32: [m [K  [01;31m [Kerror:  [m [K‘ [01m [Krand [m [K’ was not declared in this scope
                 data[j] = rand() % 16;
```