Harden `curl` usage - add retries and error logging (#1484)
The change in https://github.com/hazelcast/hazelcast-docker/pull/1284
ensured failure was reported and the execution was halted, but the error
message [wasn't
clear](https://github.com/hazelcast/hazelcast-docker/actions/runs/28910263431/job/85765974279#step:6:31):
> Error: Process completed with exit code 22.

By adding the [`--show-error`
option](https://curl.se/docs/manpage.html#--show-error) we can ensure
the human readable error is printed to stderr, e.g.:
> curl: (56) The requested URL returned error: 404


In addition, the root cause of the failure is _probably_ an intermittent
blip on the GitHub side ([related
discussion](https://github.com/orgs/community/discussions/53538)) - so
adding a simple retry-on-failure seems sensible.