Fixed build problems with latest Boost library versions and workflow changes [DEX-431] [CTT-734][CTT-716] (#1322)
Fixed build problems with latest Boost library versions.

Verification pr build is
[HERE](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/18595861858).
I had to verify this PR on origin branch **new_boost_fixes** since we
also change the workflow, hence, please check this test run to see that
all tests in all environments actually passed and we can **actually
force merge** this PR.

Updated the project to use the minimum C++ standard to be the same as
the one required by the Boost library. This means if a user is using an
older Boost version we use C++11 but if newer Boost version is used we
change level to C++ 14 since the [Math library minimum requirement
became
C++14](https://github.com/boostorg/math/releases/tag/boost-1.82.0)
starting with Boost 1.82.0.

    # Check Boost version and set C++ standard accordingly
# Our library can not use a lower C++ standard than the one required by
Boost.
    if (Boost_VERSION VERSION_LESS 1.82.0)
        set(CMAKE_CXX_STANDARD 11)
message(STATUS "Boost version ${Boost_VERSION} < 1.82.0, setting C++
standard to 11.")
    else()
        set(CMAKE_CXX_STANDARD 14)
message(STATUS "Boost version ${Boost_VERSION} >= 1.82.0, setting C++
standard to 14. "
                "Boost.Math library requires minimum C++14 compiler.")
    endif()

Changed the PR builder boost version to latest version of Boost 1.89.0.

The lazy partition assignment is causing problem with partition updates.
Hence, I had to to port the following Java PR client related parts to
the C++ client as well:
https://github.com/hazelcast/hazelcast/pull/16375

fixes #1253 
fixes https://hazelcast.atlassian.net/browse/DEX-431

I tried to separate the workflows changes from other changes but that
attempt failed at
[here](https://github.com/hazelcast/hazelcast-cpp-client/pull/1334). We
bump into a problem which is due to update of the new LLVM compiler
which does more strict checking of the template class methods. This
caused a bug in boost become apparent and it is only fixed at Boost
1.88.0. When I bump the Boost version, I also have to change the
workflow since the versions are [hard coded into the workflow
build-pr](https://github.com/hazelcast/hazelcast-cpp-client/blob/db3b3d83c70491d1e6905d220d96035de8350623/.github/workflows/build-pr.yml#L27).
Hence, separation attempt fails.

**Important Note:** There is a problem with Windows NO-SSL builds,
hence, I currently enable SSL even for no-ssl builds until this problem
is solved. The windows no-ssl builds fail with many errors like:

```
     5>C:\Boost\include\boost-1_89\boost\uuid\detail\chacha20.hpp(136,34): error C2059: syntax error: ')' [D:\a\hazelcast-cpp-client\hazelcast-cpp-client\build\hazelcast\test\src\client_test.vcxproj]
         (compiling source file '../../../../hazelcast/test/src/ClientTest.cpp')
         
     5>C:\Boost\include\boost-1_89\boost\uuid\detail\chacha20.hpp(136,34): error C2334: unexpected token(s) preceding ':'; skipping apparent function body [D:\a\hazelcast-cpp-client\hazelcast-cpp-client\build\hazelcast\test\src\client_test.vcxproj]
         (compiling source file '../../../../hazelcast/test/src/ClientTest.cpp')

```
[This](https://github.com/hazelcast/hazelcast-cpp-client/issues/1328)
windows build issue needs to be resolved before we do any releases but I
do not want it block this PR since I already spent good amount of time
without a solution.