Adding a step to sync log file content to filesystem. Failure to do this most probably caused some test failure at windows. The easylogging++ library by default flushes the context but it does not sync since it more expensive. Hence, i believe this may have been the reason for some windows test failures. The failures at windows were:
[  FAILED  ] LoggerConfigFromFileTest.testFinest
[  FAILED  ] LoggerConfigFromFileTest.testMultipleLinesLog
LoggerConfigFromFIleTest.cpp(69): error: Value of: lines.size()
   Actual: 0
  Expected: 1U
  Which is: 1