Fix windows builds release builds failures and warnings (#668)
* Fixed build warnings and errors at windows. The errors:
```
error LNK2019: unresolved external symbol "public: virtual __thiscall hazelcast::client::spi::impl::ClientInvocationServiceImpl::ResponseProcessor::~ResponseProcessor(void)"
```

The warnings:
```
LifecycleListener.h(180,49): warning C4251: 'hazelcast::client::LifecycleListener::starting': class 'std::function<void (void)>' needs to have dll-interface to be used by clients of class 'hazelcast::client::LifecycleListener'
```

* Bug and warning fix, do not forget to return the correct substring for method `raft_proxy_factory::without_default_group_name`.

* Add config type to windows build script.

* added cmake configuration type.

* Fix to cmake to choose the right version of boost library to link on windows.