Solved conflict with mysql-dev (#519)
* Solved what is conflict with mysql

fixes https://github.com/hazelcast/hazelcast-cpp-client/issues/518

* In file included from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/ClientInvocationFuture.h:23:0,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h:28,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/ClientInvocationService.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/proxy/ProxyImpl.h:28,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/proxy/IMapImpl.h:26,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/ClientMapProxy.h:31,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/impl/ClientMapProxyFactory.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h:26,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/HazelcastClient.h:19,
                 from /tmp/tmp.Nw0IPD6ru3/src/main.cpp:25:
/root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/AbstractInvocationFuture.h:426:51: error: reference to 'Runnable' is ambiguous
                     class CallbackRunner : public Runnable {

* In file included from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/ClientInvocationFuture.h:23:0,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h:28,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/ClientInvocationService.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/proxy/ProxyImpl.h:28,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/proxy/IMapImpl.h:26,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/ClientMapProxy.h:31,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/impl/ClientMapProxyFactory.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h:26,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/HazelcastClient.h:19,
                 from /tmp/tmp.Nw0IPD6ru3/src/main.cpp:25:
/root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/AbstractInvocationFuture.h:426:51: error: reference to 'Runnable' is ambiguous
                     class CallbackRunner : public Runnable {

* In file included from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/ClientInvocationFuture.h:23:0,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h:28,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/ClientInvocationService.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/proxy/ProxyImpl.h:28,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/proxy/IMapImpl.h:26,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/ClientMapProxy.h:31,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/map/impl/ClientMapProxyFactory.h:22,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h:26,
                 from /root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/HazelcastClient.h:19,
                 from /tmp/tmp.Nw0IPD6ru3/src/main.cpp:25:
/root/hazelcast-cpp-client/hazelcast/include/hazelcast/client/spi/impl/AbstractInvocationFuture.h:426:51: error: reference to 'Runnable' is ambiguous
                     class CallbackRunner : public Runnable {

* exception::TimeoutException