Removed the unneeded use of NULL in comparison which caused problems at gcc4.8.5 centos7 environment.The error was:
PortableSerializer.h>:75:41: error:  NULL was not declared in this scope
                         if ((Portable *)NULL == portableInstance.get()) {