Make project compile with boost 1.74 or later (#735)
* Removed "using namespaces" statements.

* Changed the way that we use the socket strands. This is more portable and works with both old and new boost versions.

* Bumped up the boost version to latest 1.75.0 version.

Added the -Wno-maybe-uninitialized flag for debug build to bypass the error due to an unused variable in googletest source code:
``gtest-death-test.cc:1301:24: error: 'dummy' may be used uninitialized [-Werror=maybe-uninitialized]`

* Refactored `hz_socket` class name back into `socket`.