Fixed build warnings and errors at windows. The errors: ``` error LNK2019: unresolved external symbol "public: virtual __thiscall hazelcast::client::spi::impl::ClientInvocationServiceImpl::ResponseProcessor::~ResponseProcessor(void)" ```
The warnings:
```
LifecycleListener.h(180,49): warning C4251: 'hazelcast::client::LifecycleListener::starting': class 'std::function<void (void)>' needs to have dll-interface to be used by clients of class 'hazelcast::client::LifecycleListener'
```